spring:
  profiles: default

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
        ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/vehicle
    username: postgres
    password: increible2009

server:
   port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    non-secure-port: 8080


